name: Build documentation
on: workflow_dispatch

jobs:
  build-docs:
    runs-on: ubuntu-20.04
    container:
      image: qgis/qgis:release-3_16
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fix Python command
        run: apt-get install python-is-python3

      - name: Install poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install plugin dependencies
        run: poetry install

      - name: Generate plugin repo XML
        run: poetry run python admin.py --verbose generate-plugin-repo-xml

      - name: Update the documentation
        run: poetry run mkdocs gh-deploy --force