name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    branches:
      - main

env:
  # Global environment variable
  IMAGE: qgis/qgis
  WITH_PYTHON_PEP: "true"
  MUTE_LOGS: "true"

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Running tests on QGIS ${{ matrix.qgis_version_tag }}

    strategy:
      fail-fast: false
      matrix:
        qgis_version_tag:
          - release-3_16
          - release-3_20
          - release-3_22
          - release-3_24
          - final-3_26_0

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Preparing docker-compose environment
        env:
          QGIS_VERSION_TAG: ${{ matrix.qgis_version_tag }}
        run: |
          cat << EOF > .env
          QGIS_VERSION_TAG=${QGIS_VERSION_TAG}
          IMAGE=${IMAGE}
          ON_TRAVIS=true
          MUTE_LOGS=${MUTE_LOGS}
          WITH_PYTHON_PEP=${WITH_PYTHON_PEP}
          EOF
      - name: Install poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: 1.2.2

      - name: Install plugin dependencies
        run: poetry install

      - name: Preparing test environment
        run: |
          cat .env
          docker pull "${IMAGE}":${{ matrix.qgis_version_tag }}
          poetry run python admin.py build --tests
          docker-compose up -d
          sleep 10

      - name: Run test suite
        run: |
          docker-compose exec -T qgis-testing-environment sh -c "pip3 install flask"
          docker-compose exec -T qgis-testing-environment qgis_testrunner.sh test_suite.test_package

  test2:
    name: Run PSScriptAnalyzer on Windows
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        qgis_version_tag:
          - release-3_16
          - release-3_20
          - release-3_22
          - release-3_24
          - final-3_26_0

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
#      - uses: actions/checkout@v3

      - name: Preparing docker-compose environment
        env:
          QGIS_VERSION_TAG: ${{ matrix.qgis_version_tag }}
        run: |
          cat << EOF > .env
          QGIS_VERSION_TAG=${QGIS_VERSION_TAG}
          IMAGE=${IMAGE}
          ON_TRAVIS=true
          MUTE_LOGS=${MUTE_LOGS}
          WITH_PYTHON_PEP=${WITH_PYTHON_PEP}
          EOF

      - name: Install PSScriptAnalyzer module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -ErrorAction Stop
      - name: Get list of rules
        shell: pwsh
        run: |
          Get-ScriptAnalyzerRule